### ISSUE TITLE
40 channel sniffing

### ISSUE THREAD

**Issue by GatCode** [mikeryan/ice9-bluetooth-sniffer#10]
Sorry for asking but you mentioned that ICE9 is able to listen to 4-40 channels simultaneously. But neither the HackRF, BladeRF and USRP (cheaper series) support the full 80MHz required for all 40 channels. Can you please elaborate on the 40 channel sniffing and how this could be done?

**Comment by alphafox02** [comment]
The BladeRF on DragonOS w/ new Nuand/GR-OsmoSDR settings supports 122Mhz wide.

https://www.nuand.com/2023-02-release-122-88mhz-bandwidth/

**Comment by GatCode** [comment]
Aah alright, thank you!
