### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by amitpathania** [mikeryan/ice9-bluetooth-sniffer#13]
Getting errors while running make command.

/home/star/Documents/ice9-bluetooth-sniffer/bladerf.c: In function ‘bladerf_setup’:
/home/star/Documents/ice9-bluetooth-sniffer/bladerf.c:61:19: error: implicit declaration of function ‘bladerf_enable_feature’; did you mean ‘bladerf_enable_module’? [-Werror=implicit-function-declaration]
     if ((status = bladerf_enable_feature(bladerf, BLADERF_FEATURE_OVERSAMPLE, true)) != 0)
                   ^~~~~~~~~~~~~~~~~~~~~~
                   bladerf_enable_module
/home/star/Documents/ice9-bluetooth-sniffer/bladerf.c:61:51: error: ‘BLADERF_FEATURE_OVERSAMPLE’ undeclared (first use in this function); did you mean ‘BLADERF_ERR_RANGE’?
     if ((status = bladerf_enable_feature(bladerf, BLADERF_FEATURE_OVERSAMPLE, true)) != 0)
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   BLADERF_ERR_RANGE
/home/star/Documents/ice9-bluetooth-sniffer/bladerf.c:61:51: note: each undeclared identifier is reported only once for each function it appears in
/home/star/Documents/ice9-bluetooth-sniffer/bladerf.c: In function ‘bladerf_stream_thread’:
/home/star/Documents/ice9-bluetooth-sniffer/bladerf.c:109:97: error: ‘BLADERF_FORMAT_SC8_Q7’ undeclared (first use in this function); did you mean ‘BLADERF_FORMAT_SC16_Q11’?
     if ((status = bladerf_init_stream(&stream, bladerf, bladerf_rx_cb, &buffers, num_transfers, BLADERF_FORMAT_SC8_Q7, channels / 2 * 4096, num_transfers, NULL)) != 0)
                                                                                                 ^~~~~~~~~~~~~~~~~~~~~
                                                                                                 BLADERF_FORMAT_SC16_Q11
cc1: some warnings being treated as errors
CMakeFiles/ice9-bluetooth.dir/build.make:66: recipe for target 'CMakeFiles/ice9-bluetooth.dir/bladerf.c.o' failed
make[2]: *** [CMakeFiles/ice9-bluetooth.dir/bladerf.c.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/ice9-bluetooth.dir/all' failed
make[1]: *** [CMakeFiles/ice9-bluetooth.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mikeryan** [comment]
Hi, you have two options if you face this error:

- use `libbladerf 2.5.0` or newer
- use the release [v23.02.0](https://github.com/mikeryan/ice9-bluetooth-sniffer/releases/tag/v23.02.0)

Or option three is wait a few days for me to make the necessary cmake changes to detect older versions of libbladerf.

**Comment by mikeryan** [comment]
I guess it took less than a few days. Let me know if you still have trouble.
