### ISSUE TITLE
[ERROR @ /privatehost/libraries/libbladeRF/src/board/bladerf2/bladerf2.c:1241] bladerf2_set_frequency: Board state insufficient for operation (current "Firmware Loaded", requires "Initialized")

### ISSUE THREAD

**Issue by jsmif** [mikeryan/ice9-bluetooth-sniffer#17]
I just pulled a BladeRF out of the box, connected the antennas and USB, installed the prereqs and built on Mac. When I do

`./ice9-bluetooth -l -c 2427 -C 20 -w ble.pcap -i bladerf0`
I get
```
[WARNING @ /privatehost/libraries/libbladeRF/src/board/bladerf2/bladerf2.c:461] FPGA bitstream file not found.
[WARNING @ /privatehost/libraries/libbladeRF/src/board/bladerf2/bladerf2.c:462] Skipping further initialization...
[ERROR @ /privatehost/libraries/libbladeRF/src/board/bladerf2/bladerf2.c:1241] bladerf2_set_frequency: Board state insufficient for operation (current "Firmware Loaded", requires "Initialized").
ice9-bluetooth: Unable to set bladeRF center frequency: Insufficient initialization for the requested operation
```

Is there an additional setup step that isn't mentioned on the README.md that I should be doing to initialize the bitstream?

**Comment by mikeryan** [comment]
Yes, you must either load the latest FPGA image or flash it onto the onboard flash. It can be found here for the xA4:

https://www.nuand.com/fpga/hostedxA4-latest.rbf

Load it using `bladerf-cli -l hostedxA4-latest.rbf`.

For the other models, look here: https://www.nuand.com/fpga_images/

**Comment by mikeryan** [comment]
Yep, the warning about 2.5.0 is safe to ignore. Give all-channel sniffing a try and see if your machine can keep up!

**Comment by mikeryan** [comment]
As long as you're doing realtime capture, the channelizer will always show as 100ish% or less. If you want to benchmark your system, try `/dev/urandom` on Linux or `/dev/random` on macOS.
