### ISSUE TITLE
Cannot sniff packets while use l2ping

### ISSUE THREAD

**Issue by trungchubao** [mikeryan/ice9-bluetooth-sniffer#23]
I have a head unit (car) which can pair with iphones using Bluetooth. I started ice9-bluetooth-sniffer with hackrf, it grabbed many packets. Given that, I tried to pair my phone with the head unit, but no packet related to that was captured.

I would assume that the head unit is a nondiscoverable device. Is it possible for ice9-bluetooth-sniffer to capture packets from/to such nondiscoverable device? Any hints/suggestions would be greatly appreciated!

**Comment by trungchubao** [comment]
As the title of the issue, I also tried to use l2ping to send ping packet to the head unit. But no packet was captured either.

**Comment by mringwal** [comment]
unrelated to the this project: you can get an HCI trace from iOS devices directly for analysis
https://www.bluetooth.com/blog/a-new-way-to-debug-iosbluetooth-applications/

**Comment by mikeryan** [comment]
Hi @trungchubao, `l2ping` uses classic Bluetooth (along with most of the other features of your head unit). At the present time we only have limited support for classic Bluetooth sniffing, so you will not be able to sniff this connection at present. Sorry!
